### ISSUE TITLE
Fatal error :Uncaught error 

### ISSUE THREAD

**Issue by dammzie** [mohsinenur/Daowat-Social-Network#2]
There is an error in d connect.ini.php and Index.php not loading , it's saying 

fatal error: Uncaught error : call to undefined functions mysql_connect() in C:\.....\inc\connect.inc.php:2 stack trace : #0 C:\......\index.php(1): include() #1 {main} thrown in C:\ ......\inc \connect.inc.php on line 2

it's not connecting for Db name -daowat_db, db-user - root , db-pass "" .. Please check and correct with the code

**Comment by dammzie** [comment]
![screenshot_2018-07-23 screenshot](https://user-images.githubusercontent.com/18022666/43070882-e43ba702-8e68-11e8-89ab-9c4d89e6491f.png)

**Comment by dammzie** [comment]
<?php 
mysql_connect("localhost","daowatco_td","sinEmi4334222") or die("Couldn't connet to SQL server");
mysql_select_db("daowatco_td") or die("Couldn't select DB");

//time formate
function formatDate($date){
	return date('F j, Y, g:i a', strtotime($date));
}
 ?>


connect.inc.php
change user to root and password to be empty then db name to daowat_db

**Comment by mohsinenur** [comment]
every one using this code without any error. only you can not do this. Please forget this code.
